#!/bin/bash
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
#menuentry 'Ubuntu (snapshot)' {
#        linux   /ROOT/bravo/@zfsroot/boot/vmlinuz-3.13.0-32-generic root=ZFS=rpool/ROOT/bravo@zfsroot ro boot=zfs
#        initrd  /ROOT/bravo/@zfsroot/boot/initrd.img-3.13.0-32-generic
#}
rpool=rpool # name of root pool

[[ -f /etc/default/grub ]] && . /etc/default/grub
DIST=${GRUB_DISTRIBUTOR:-"Linux"}

snapdir=/.zfs/snapshot
first=0
rootfs=$(mount | grep 'on / type' | sed "s!^.*on / type !!" | cut -d ' ' -f 1)
[ "$rootfs" != "zfs" ] && exit 0

# we have a zfs root file systems
ROOT=$(mount | grep 'on / type' | cut -d ' ' -f 1)
SROOT=$(echo $ROOT | sed "s:^$rpool::")


make_entry ()
{
echo Adding snapshot selection entries for $1$2 >$2
cat <<!
	menuentry 'ZFS snapshot selection $1$2' {
		linux   ${SROOT}/@/$1$2 root=ZFS=${ROOT}@ ro boot=zfs
		initrd  ${SROOT}/@/initrd.img$2
	}
!
}

make_entry vmlinuz
make_entry vmlinuz .old

# vim: sw=2:ai:nu 
