#!/bin/bash
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
#menuentry 'Ubuntu (snapshot)' {
#        linux   /ROOT/bravo/@zfsroot/boot/vmlinuz-3.13.0-32-generic root=ZFS=POOL/ROOT/bravo@zfsroot ro boot=zfs
#        initrd  /ROOT/bravo/@zfsroot/boot/initrd.img-3.13.0-32-generic
#}

MNTINFO=$(mount | grep 'on / type')
[[ ${MNTINFO} = *zfs* ]] || exit 0
# we have a zfs root file system

BOOTEDROOT=${MNTINFO%% *}
oIFS=$IFS
IFS=/ PARTS=( ${BOOTEDROOT} )
IFS=$oIFS
POOL=${PARTS[0]}
BEDS=${PARTS[1]}
#BE=${PARTS[2]}

MNTDIR=/tmp/grub$$
mkdir ${MNTDIR} || true

[[ -f /etc/default/grub ]] && . /etc/default/grub
DIST=${GRUB_DISTRIBUTOR:-"Linux"}

echowtabs()
{
  tabs=$1
  shift
  for ((i=0; i<$tabs; i++))
  do
    echo -n "	"
  done
  echo $*
}

make_entry()
{
  local _mntdir=$1
  local _fs=$2
  declare -i _indent=${3:-0}

  rootfs=${_fs%%@*}
  be=${rootfs##*/}
  snap=${fs#*@}
  snapname=${snap}/
  [[ ${snap} ]] && entry="@${snap}" || entry=""
 
  ${MOUNT} ${_mntdir} >&2
  if [[ -d ${_mntdir}/boot/ ]]
  then
    for version in $(cd ${_mntdir}/boot; ls vmlinuz-* | grep -v old-dkms | tac)
    do
      version=$(echo $version | sed 's/^vmlinuz-//')
      if [[ -f ${_mntdir}/boot/vmlinuz-$version && -f ${_mntdir}/boot/initrd.img-$version ]] 
      then
	echo "Found kernel image: $version on ${_fs}" >&2
	#echowtabs ${_indent} "menuentry '$DIST ${be} $version ($(zfs list -H -o creation ${_fs}))' {"
	echowtabs ${_indent} "menuentry '$DIST, boot environment ${be}${entry}, with Linux $version ($(zfs list -H -o creation ${_fs})) {"
	echowtabs ${_indent}+1 "	linux   /${BEDS}/${be}/@${snapname}boot/vmlinuz-$version root=ZFS=${_fs} ro boot=zfs"
	echowtabs ${_indent}+1 "	initrd  /${BEDS}/${be}/@${snapname}boot/initrd.img-$version"
	echowtabs ${_indent} "}"
      fi
    done
  fi
  ${UMOUNT} >&2
}

echo "# Auto generated zfs boot environment and snapshot entries"

BELIST=$({
if [[ $(which beadm) ]]
then
  beadm list -H | cut -f 1 | sed "s:^:${POOL}/${BEDS}/:"
else
  zfs list -H -r -p -o name ${POOL}/${BEDS}
fi
} | tac)
for BE in $BELIST
do
  if [[ ${BE} = ${BOOTEDROOT} ]]
  then
    MOUNT=:
    UMOUNT=:
    make_entry "" ${BE}
  else
    be="${BE##*/}"
    MOUNT="beadm mount ${be}"
    UMOUNT="beadm umount "${be}""
    make_entry ${MNTDIR} ${BE}
  fi

  echo "submenu '${DIST}, boot environment ${BE} snapshots' {"
  for fs in $(zfs list -H -r -p -t snap -o name ${BE} | tac)
  do
    MOUNT="mount -t zfs ${fs}"
    UMOUNT="umount ${MNTDIR}"
    make_entry ${MNTDIR} ${fs} 1
  done
  echo "}"
done
rmdir ${MNTDIR}

exit 0

# vim: sw=2:ai:nu 
