fixtures:
  symlinks:
    bootstrap: "#{source_dir}/site-modules/bootstrap"
    profile: "#{source_dir}/site-modules/profile"
    role: "#{source_dir}/site-modules/role"
  repositories:
    samba:
      repo: https://github.com/mergwyn/puppet-samba
      ref: master
    nginx:
      repo: https://github.com/voxpupuli/puppet-nginx
      ref: master
    unbound:
      repo: https://github.com/voxpupuli/puppet-unbound
      ref: master
    transmission:
      repo: https://github.com/craigwatson/puppet-transmission
      ref: master
    managedmac:
      repo: https://github.com/mergwyn/mergwyn-managedmac
      branch: v0.8.2
    jackett:
      repo: https://github.com/mergwyn/mergwyn-jackett
      ref: master
    radarr:
      repo: https://github.com/mergwyn/mergwyn-radarr
      ref: main
    ddclient:
      repo: https://github.com/mergwyn/puppet-ddclient
      ref: master
    webmin:
      repo: https://github.com/rehanone/puppet-webmin
      ref: master
# TODO woraround for https://github.com/puppetlabs/puppetlabs-docker/issues/870
    docker:
      repo: https://github.com/mergwyn/puppetlabs-docker
      branch: fuse-overlayfs
    backuppc:
      repo: https://github.com/mergwyn/mergwyn-backuppc
      ref: master
  forge_modules:
    alternatives:
      repo: "puppet-alternatives"
      ref: "4.2.0"
    apache:
      repo: "puppetlabs-apache"
      ref: "10.1.0"
    apt:
      repo: "puppetlabs-apt"
      ref: "9.1.0"
    archive:
      repo: "puppet-archive"
      ref: "7.0.0"
    augeas:
      repo: "camptocamp-augeas"
      ref: "1.9.0"
    augeas_core:
      repo: "puppetlabs-augeas_core"
      ref: "1.3.0"
    augeasproviders_core:
      repo: "puppet-augeasproviders_core"
      ref: "3.2.1"
    augeasproviders_pam:
      repo: "puppet-augeasproviders_pam"
      ref: "3.0.1"
    augeasproviders_shellvar:
      repo: "puppet-augeasproviders_shellvar"
      ref: "5.0.0"
    augeasproviders_sysctl:
      repo: "herculesteam-augeasproviders_sysctl"
      ref: "2.6.2"
    autofs:
      repo: "puppet-autofs"
      ref: "7.1.0"
    chocolatey:
      repo: "puppetlabs-chocolatey"
      ref: "8.0.0"
    concat:
      repo: "puppetlabs-concat"
      ref: "9.0.0"
    cron:
      repo: "puppet-cron"
      ref: "3.0.0"
    cron_core:
      repo: "puppetlabs-cron_core"
      ref: "1.2.0"
    cups:
      repo: "mosen-cups"
      ref: "1.5.0"
    debconf:
      repo: "stm-debconf"
      ref: "5.0.0"
    dhcp:
      repo: "puppet-dhcp"
      ref: "5.0.1"
    dism:
      repo: "puppetlabs-dism"
      ref: "1.3.1"
    epel:
      repo: "puppet-epel"
      ref: "4.1.0"
    exec:
      repo: "puppetlabs-exec"
      ref: "3.0.0"
    exports:
      repo: "zack-exports"
      ref: "1.0.1"
    firewall:
      repo: "puppetlabs-firewall"
      ref: "5.0.0"
    firewalld:
      repo: "puppet-firewalld"
      ref: "4.5.1"
    git:
      repo: "puppetlabs-git"
      ref: "0.5.0"
    githubreleases:
      repo: "dodevops-githubreleases"
      ref: "4.0.0"
    homebrew:
      repo: "thekevjames-homebrew"
      ref: "1.9.1"
    host_core:
      repo: "puppetlabs-host_core"
      ref: "1.2.0"
    inifile:
      repo: "puppetlabs-inifile"
      ref: "6.0.0"
    keepalived:
      repo: "puppet-keepalived"
      ref: "3.6.0"
    kmod:
      repo: "puppet-kmod"
      ref: "4.0.1"
    #letsencrypt:
      #repo: "puppet-letsencrypt"
      #ref: "9.2.0"
    libvirt:
      repo: "thias-libvirt"
      ref: "1.0.2"
    mailalias_core:
      repo: "puppetlabs-mailalias_core"
      ref: "1.1.0"
    mount_core:
      repo: "puppetlabs-mount_core"
      ref: "1.2.0"
    mysql:
      repo: "puppetlabs-mysql"
      ref: "14.0.0"
    netplan:
      repo: "zehweh-netplan"
      ref: "1.0.1"
    ntp:
      repo: "puppetlabs-ntp"
      ref: "10.0.0"
    php:
      repo: "puppet-php"
      ref: "8.2.0"
    portage:
      repo: "gentoo-portage"
      ref: "2.3.0"
    postfix:
      repo: "puppet-postfix"
      ref: "4.0.0"
    postgresql:
      repo: "puppetlabs-postgresql"
      ref: "9.1.0"
    powershell:
      repo: "puppetlabs-powershell"
      ref: "6.0.0"
    puppetboard:
      repo: "puppet-puppetboard"
      ref: "10.0.0"
    puppetdb:
      repo: "puppetlabs-puppetdb"
      ref: "7.13.0"
    puppetserver_gem:
      repo: "puppetlabs-puppetserver_gem"
      ref: "1.1.1"
    pwshlib:
      repo: "puppetlabs-pwshlib"
      ref: "0.10.3"
    python:
      repo: "puppet-python"
      ref: "6.4.0"
    r10k:
      repo: "puppet-r10k"
      ref: "11.0.1"
    reboot:
      repo: "puppetlabs-reboot"
      ref: "5.0.0"
    registry:
      repo: "puppetlabs-registry"
      ref: "5.0.0"
    scheduled_task:
      repo: "puppetlabs-scheduled_task"
      ref: "4.0.0"
    selinux:
      repo: "puppet-selinux"
      ref: "3.4.1"
    snapd:
      repo: "ethanhs-snapd"
      ref: "1.4.0"
    ssh:
      repo: "saz-ssh"
      ref: "10.2.0"
    sshkeys_core:
      repo: "puppetlabs-sshkeys_core"
      ref: "2.4.0"
    sssd:
      repo: "sgnl05-sssd"
      ref: "3.1.0"
    stdlib:
      repo: "puppetlabs-stdlib"
      ref: "9.1.0"
    sudo:
      repo: "saz-sudo"
      ref: "7.0.2"
    systemd:
      repo: "puppet-systemd"
      ref: "5.1.0"
    timezone:
      repo: "saz-timezone"
      ref: "6.3.0"
    unattended_upgrades:
      repo: "puppet-unattended_upgrades"
      ref: "8.0.0"
    vcsrepo:
      repo: "puppetlabs-vcsrepo"
      ref: "6.1.0"
    xinetd:
      repo: "puppetlabs-xinetd"
      ref: "3.3.0"
    yumrepo_core:
      repo: "puppetlabs-yumrepo_core"
      ref: "2.0.0"
    zabbix:
      repo: "puppet-zabbix"
      ref: "9.2.0"
