---
fixtures:
  symlinks:
    bootstrap: "#{source_dir}/site-modules/bootstrap"
    profile: "#{source_dir}/site-modules/profile"
    role: "#{source_dir}/site-modules/role"
  repositories:
    homebrew:
      repo: https://github.com/mergwyn/puppet-homebrew
      ref: master
    backuppc:
      repo: https://github.com/mergwyn/mergwyn-backuppc
      ref: master
    transmission:
      repo: https://github.com/craigwatson/puppet-transmission
      ref: master
    samba:
      repo: https://github.com/mergwyn/mergwyn-samba
      ref: master
    managedmac:
      repo: https://github.com/mergwyn/mergwyn-managedmac
      branch: v0.8.2
    ddclient:
      repo: https://github.com/mergwyn/puppet-ddclient
      ref: master
    jackett:
      repo: https://github.com/mergwyn/mergwyn-jackett
      ref: master
    radarr:
      repo: https://github.com/mergwyn/mergwyn-radarr
      ref: main
    docker:
      repo: https://github.com/mergwyn/puppetlabs-docker
      branch: fuse-overlayfs
    nginx:
      repo: https://github.com/voxpupuli/puppet-nginx
      ref: master
    unbound:
      repo: https://github.com/voxpupuli/puppet-unbound
      ref: master
    webmin:
      repo: https://github.com/rehanone/puppet-webmin
      ref: master
  forge_modules:
    augeas:
      repo: camptocamp/augeas
      ref: 1.9.0
    githubreleases:
      repo: dodevops/githubreleases
      ref: 4.1.0
    snap:
      repo: rootexpert-snap
      ref: 2.0.0
    portage:
      repo: gentoo/portage
      ref: 2.3.0
    cups:
      repo: mosen/cups
      ref: 1.5.0
    alternatives:
      repo: puppet/alternatives
      ref: 5.1.0
    archive:
      repo: puppet/archive
      ref: 7.1.0
    augeasproviders_core:
      repo: puppet/augeasproviders_core
      ref: 4.1.0
    augeasproviders_pam:
      repo: puppet/augeasproviders_pam
      ref: 4.0.0
    augeasproviders_shellvar:
      repo: puppet/augeasproviders_shellvar
      ref: 6.0.1
    augeasproviders_sysctl:
      repo: puppet/augeasproviders_sysctl
      ref: 3.2.0
    autofs:
      repo: puppet/autofs
      ref: 9.0.0
    cron:
      repo: puppet/cron
      ref: 4.1.0
    dhcp:
      repo: puppet/dhcp
      ref: 6.1.0
    epel:
      repo: puppet/epel
      ref: 5.0.0
    firewalld:
      repo: puppet/firewalld
      ref: 5.0.0
    keepalived:
      repo: puppet/keepalived
      ref: 4.0.0
    kmod:
      repo: puppet/kmod
      ref: 4.0.1
    apache:
      repo: puppetlabs/apache
      ref: 12.1.0
    apt:
      repo: puppetlabs/apt
      ref: 9.4.0
    augeas_core:
      repo: puppetlabs/augeas_core
      ref: 1.5.0
    firewall:
      repo: puppetlabs/firewall
      ref: 7.0.2
    git:
      repo: puppetlabs/git
      ref: 0.5.0
    inifile:
      repo: puppetlabs/inifile
      ref: 6.1.1
    mailalias_core:
      repo: puppetlabs/mailalias_core
      ref: 1.1.0
    mysql:
      repo: puppetlabs/mysql
      ref: 15.0.0
    ntp:
      repo: puppetlabs/ntp
      ref: 10.1.0
    postgresql:
      repo: puppetlabs-postgresql
      ref: 10.3.0
    puppetdb:
      repo: puppetlabs/puppetdb
      ref: 8.1.0
    puppetserver_gem:
      repo: puppetlabs/puppetserver_gem
      ref: 1.1.1
    reboot:
      repo: puppetlabs/reboot
      ref: 5.0.0
    sshkeys_core:
      repo: puppetlabs/sshkeys_core
      ref: 2.5.0
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.6.0
    vcsrepo:
      repo: puppetlabs/vcsrepo
      ref: 6.1.0
    xinetd:
      repo: puppetlabs/xinetd
      ref: 3.4.1
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
      ref: 2.1.0
    logrotate:
      repo: puppet/logrotate
      ref: 7.0.2
    php:
      repo: puppet/php
      ref: 10.1.0
    postfix:
      repo: puppet/postfix
      ref: 4.4.0
    puppetboard:
      repo: puppet/puppetboard
      ref: 10.0.0
    python:
      repo: puppet/python
      ref: 7.3.0
    r10k:
      repo: puppet/r10k
      ref: 12.2.0
    selinux:
      repo: puppet/selinux
      ref: 4.1.0
    systemd:
      repo: puppet/systemd
      ref: 7.1.0
    unattended_upgrades:
      repo: puppet/unattended_upgrades
      ref: 8.1.0
    zabbix:
      repo: puppet/zabbix
      ref: 10.0.0
    ssh:
      repo: saz/ssh
      ref: 12.1.0
    sudo:
      repo: saz/sudo
      ref: 8.0.0
    timezone:
      repo: saz/timezone
      ref: 7.0.0
    sssd:
      repo: sgnl05/sssd
      ref: 3.1.0
    debconf:
      repo: stm/debconf
      ref: 6.0.0
    libvirt:
      repo: thias/libvirt
      ref: 1.0.2
    exports:
      repo: zack/exports
      ref: 1.0.1
    netplan:
      repo: zehweh/netplan
      ref: 2.0.0
    host_core:
      repo: puppetlabs/host_core
      ref: 1.3.0
    mount_core:
      repo: puppetlabs/mount_core
      ref: 1.3.0
    cron_core:
      repo: puppetlabs/cron_core
      ref: 1.3.0
    exec:
      repo: puppetlabs/exec
      ref: 3.0.0
    chocolatey:
      repo: puppetlabs/chocolatey
      ref: 8.0.0
    dism:
      repo: puppetlabs/dism
      ref: 1.3.1
    registry:
      repo: puppetlabs/registry
      ref: 5.0.1
    concat:
      repo: puppetlabs/concat
      ref: 9.0.2
    scheduled_task:
      repo: puppetlabs/scheduled_task
      ref: 4.0.0
    powershell:
      repo: puppetlabs/powershell
      ref: 6.0.0
    pwshlib:
      repo: puppetlabs/pwshlib
      ref: 1.1.1
