---
fixtures:
  symlinks:
    role: "#{source_dir}/site-modules/role"
    profile: "#{source_dir}/site-modules/profile"
  repositories:
    unbound:
      repo: https://github.com/voxpupuli/puppet-unbound
      ref: master
    transmission:
      repo: https://github.com/craigwatson/puppet-transmission
      ref: master
    managedmac:
      repo: https://github.com/mergwyn/mergwyn-managedmac
      branch: v0.8.2
    jackett:
      repo: https://github.com/mergwyn/mergwyn-jackett
      ref: master
    radarr:
      repo: https://github.com/mergwyn/mergwyn-radarr
      ref: main
    ddclient:
      repo: https://github.com/mergwyn/puppet-ddclient
      ref: master
    dhcp:
      repo: https://github.com/voxpupuli/puppet-dhcp
      ref: master
    webmin:
      repo: https://github.com/rehanone/puppet-webmin
      ref: master
    backuppc:
      repo: https://github.com/mergwyn/mergwyn-backuppc
      ref: master
    zabbix:
      repo: https://github.com/voxpupuli/puppet-zabbix
      ref: master
  forge_modules:
    augeas:
      repo: camptocamp-augeas
      ref: 1.9.0
    kmod:
      repo: puppet-kmod
      ref: 3.0.0
    postfix:
      repo: puppet-postfix
      ref: 2.0.0
    systemd:
      repo: puppet-systemd
      ref: 3.5.2
    githubreleases:
      repo: dodevops-githubreleases
      ref: 4.0.0
    portage:
      repo: gentoo-portage
      ref: 2.3.0
    ssh:
      repo: saz-ssh
      ref: 8.0.0
    augeasproviders_core:
      repo: herculesteam-augeasproviders_core
      ref: 3.1.0
    augeasproviders_pam:
      repo: herculesteam-augeasproviders_pam
      ref: 2.3.0
    augeasproviders_shellvar:
      repo: herculesteam-augeasproviders_shellvar
      ref: 4.1.0
    augeasproviders_sysctl:
      repo: herculesteam-augeasproviders_sysctl
      ref: 2.6.2
    samba:
      repo: kakwa-samba
      ref: 2.0.0
    snapd:
      repo: ethanhs-snapd
      ref: 1.4.0
    cups:
      repo: mosen-cups
      ref: 1.5.0
    alternatives:
      repo: puppet-alternatives
      ref: 4.0.0
    archive:
      repo: puppet-archive
      ref: 6.0.2
    autofs:
      repo: puppet-autofs
      ref: 6.0.0
    cron:
      repo: puppet-cron
      ref: 3.0.0
    firewalld:
      repo: puppet-firewalld
      ref: 4.4.0
    keepalived:
      repo: puppet-keepalived
      ref: 3.2.0
    php:
      repo: puppet-php
      ref: 8.0.2
    apache:
      repo: puppetlabs-apache
      ref: 7.0.0
    apt:
      repo: puppetlabs-apt
      ref: 8.3.0
    augeas_core:
      repo: puppetlabs-augeas_core
      ref: 1.2.0
    firewall:
      repo: puppetlabs-firewall
      ref: 3.3.0
    git:
      repo: puppetlabs-git
      ref: 0.5.0
    inifile:
      repo: puppetlabs-inifile
      ref: 5.2.0
    mailalias_core:
      repo: puppetlabs-mailalias_core
      ref: 1.1.0
    mysql:
      repo: puppetlabs-mysql
      ref: 12.0.1
    ntp:
      repo: puppetlabs-ntp
      ref: 9.1.0
    postgresql:
      repo: puppetlabs-postgresql
      ref: 7.5.0
    puppetdb:
      repo: puppetlabs-puppetdb
      ref: 7.10.0
    puppetserver_gem:
      repo: puppetlabs-puppetserver_gem
      ref: 1.1.1
    reboot:
      repo: puppetlabs-reboot
      ref: 4.1.0
    sshkeys_core:
      repo: puppetlabs-sshkeys_core
      ref: 2.3.0
    stdlib:
      repo: puppetlabs-stdlib
      ref: 8.1.0
    vcsrepo:
      repo: puppetlabs-vcsrepo
      ref: 5.0.0
    xinetd:
      repo: puppetlabs-xinetd
      ref: 3.3.0
    yumrepo_core:
      repo: puppetlabs-yumrepo_core
      ref: 1.1.0
    epel:
      repo: puppet-epel
      ref: 4.0.0
    letsencrypt:
      repo: puppet-letsencrypt
      ref: 8.0.1
    nginx:
      repo: puppet-nginx
      ref: 3.3.0
    puppetboard:
      repo: https://github.com/mergwyn/puppet-puppetboard
      ref: master
#      repo: puppet-puppetboard
#      ref: 8.1.0
    python:
      repo: puppet-python
      ref: 6.2.1
    r10k:
      repo: puppet-r10k
      ref: 10.1.1
    selinux:
      repo: puppet-selinux
      ref: 3.4.1
    unattended_upgrades:
      repo: puppet-unattended_upgrades
      ref: 6.0.0
#    zabbix:
#      repo: puppet-zabbix
#      ref: 9.1.0
    sudo:
      repo: saz-sudo
      ref: 7.0.2
    timezone:
      repo: saz-timezone
      ref: 6.1.0
    sssd:
      repo: sgnl05-sssd
      ref: 3.1.0
    debconf:
      repo: stm-debconf
      ref: 4.1.0
    homebrew:
      repo: thekevjames-homebrew
      ref: 1.9.1
    libvirt:
      repo: thias-libvirt
      ref: 1.0.1
    exports:
      repo: zack-exports
      ref: 1.0.1
    netplan:
      repo: zehweh-netplan
      ref: 1.0.0
    host_core:
      repo: puppetlabs-host_core
      ref: 1.1.0
    mount_core:
      repo: puppetlabs-mount_core
      ref: 1.1.0
    cron_core:
      repo: puppetlabs-cron_core
      ref: 1.1.0
    bootstrap:
      repo: puppetlabs-bootstrap
      ref: 2.1.0
    exec:
      repo: puppetlabs-exec
      ref: 2.0.0
    chocolatey:
      repo: puppetlabs-chocolatey
      ref: 6.0.1
    dism:
      repo: puppetlabs-dism
      ref: 1.3.1
    registry:
      repo: puppetlabs-registry
      ref: 4.0.1
    concat:
      repo: puppetlabs-concat
      ref: 7.1.1
    scheduled_task:
      repo: puppetlabs-scheduled_task
      ref: 3.0.1
    powershell:
      repo: puppetlabs-powershell
      ref: 5.0.0
    pwshlib:
      repo: puppetlabs-pwshlib
      ref: 0.10.1
