---
fixtures:
  symlinks:
    site: "#{source_dir}/site"
    profile: "#{source_dir}/site/profile"
    role: "#{source_dir}/site/role"
  repositories:
    ssh:
      repo: https://github.com/apache/puppet-module-ssh/
      branch: master
    augeasproviders_shellvar:
      repo: https://github.com/mergwyn/augeasproviders_shellvar
      branch: master
    managedmac:
      repo: https://github.com/mergwyn/mergwyn-managedmac
      branch: v0.8.2
    jackett:
      repo: https://github.com/mergwyn/mergwyn-jackett
      branch: master
    radarr:
      repo: https://github.com/mergwyn/mergwyn-radarr
      branch: master
    ddclient:
      repo: https://github.com/mergwyn/puppet-ddclient
      branch: master
    dhcp:
      repo: https://github.com/voxpupuli/puppet-dhcp
      branch: master
    transmission:
      repo: https://github.com/mergwyn/puppet-transmission
      branch: master
    webmin:
      repo: https://github.com/rehanone/puppet-webmin
      branch: master
    backuppc:
      repo: https://github.com/mergwyn/mergwyn-backuppc
      branch: master
  forge_modules:
    augeas:
      repo: camptocamp-augeas
      ref: 1.9.0
    kmod:
      repo: camptocamp-kmod
      ref: 2.5.0
    postfix:
      repo: camptocamp-postfix
      ref: 1.10.0
    systemd:
      repo: camptocamp-systemd
      ref: 2.9.0
    network:
      repo: example42-network
      ref: 3.5.3
    portage:
      repo: gentoo-portage
      ref: 2.3.0
    common:
      repo: ghoneycutt-common
      ref: 1.9.0
    augeasproviders_core:
      repo: herculesteam-augeasproviders_core
      ref: 2.6.0
    augeasproviders_pam:
      repo: herculesteam-augeasproviders_pam
      ref: 2.2.1
    samba:
      repo: kakwa-samba
      ref: 2.0.0
    snapd:
      repo: kemra102-snapd
      ref: 1.1.0
    cups:
      repo: mosen-cups
      ref: 1.5.0
    alternatives:
      repo: puppet-alternatives
      ref: 3.0.0
    archive:
      repo: puppet-archive
      ref: 4.5.0
    cron:
      repo: puppet-cron
      ref: 2.0.0
    apache:
      repo: puppetlabs-apache
      ref: 5.4.0
    apt:
      repo: puppetlabs-apt
      ref: 7.4.2
    augeas_core:
      repo: puppetlabs-augeas_core
      ref: 1.0.5
    firewall:
      repo: puppetlabs-firewall
      ref: 2.4.0
    git:
      repo: puppetlabs-git
      ref: 0.5.0
    inifile:
      repo: puppetlabs-inifile
      ref: 4.2.0
    mailalias_core:
      repo: puppetlabs-mailalias_core
      ref: 1.0.6
    mysql:
      repo: puppetlabs-mysql
      ref: 10.5.0
    ntp:
      repo: puppetlabs-ntp
      ref: 8.3.0
    postgresql:
      repo: puppetlabs-postgresql
      ref: 6.5.0
    puppetdb:
      repo: puppetlabs-puppetdb
      ref: 7.4.0
    puppetserver_gem:
      repo: puppetlabs-puppetserver_gem
      ref: 1.1.1
    reboot:
      repo: puppetlabs-reboot
      ref: 3.0.0
    ruby:
      repo: puppetlabs-ruby
      ref: 1.0.1
    sshkeys_core:
      repo: puppetlabs-sshkeys_core
      ref: 2.0.0
    stdlib:
      repo: puppetlabs-stdlib
      ref: 6.3.0
    translate:
      repo: puppetlabs-translate
      ref: 2.2.0
    vcsrepo:
      repo: puppetlabs-vcsrepo
      ref: 3.1.0
    xinetd:
      repo: puppetlabs-xinetd
      ref: 3.3.0
    yumrepo_core:
      repo: puppetlabs-yumrepo_core
      ref: 1.0.7
    epel:
      repo: puppet-epel
      ref: 3.0.1
    letsencrypt:
      repo: puppet-letsencrypt
      ref: 5.0.0
    nginx:
      repo: puppet-nginx
      ref: 1.1.0
    puppetboard:
      repo: puppet-puppetboard
      ref: 6.1.0
    python:
      repo: puppet-python
      ref: 4.1.1
    r10k:
      repo: puppet-r10k
      ref: 8.3.0
    selinux:
      repo: puppet-selinux
      ref: 3.2.0
    unattended_upgrades:
      repo: puppet-unattended_upgrades
      ref: 5.0.0
    zabbix:
      repo: puppet-zabbix
      ref: 8.0.0
    sudo:
      repo: saz-sudo
      ref: 6.0.0
    timezone:
      repo: saz-timezone
      ref: 6.0.0
    sssd:
      repo: sgnl05-sssd
      ref: 3.1.0
    debconf:
      repo: stm-debconf
      ref: 3.0.0
    homebrew:
      repo: thekevjames-homebrew
      ref: 1.8.3
    libvirt:
      repo: thias-libvirt
      ref: 1.0.0
    sysctl:
      repo: tpdownes-sysctl
      ref: 2.1.0
    exports:
      repo: zack-exports
      ref: 1.0.1
    netplan:
      repo: zehweh-netplan
      ref: 1.0.0
    host_core:
      repo: puppetlabs-host_core
      ref: 1.0.3
    mount_core:
      repo: puppetlabs-mount_core
      ref: 1.0.4
    cron_core:
      repo: puppetlabs-cron_core
      ref: 1.0.4
    bootstrap:
      repo: puppetlabs-bootstrap
      ref: 2.1.0
    exec:
      repo: puppetlabs-exec
      ref: 0.7.0
    chocolatey:
      repo: puppetlabs-chocolatey
      ref: 5.0.2
    dism:
      repo: puppetlabs-dism
      ref: 1.3.1
    registry:
      repo: puppetlabs-registry
      ref: 3.1.0
    concat:
      repo: puppetlabs-concat
      ref: 6.2.0
    scheduled_task:
      repo: puppetlabs-scheduled_task
      ref: 2.0.1
    powershell:
      repo: puppetlabs-powershell
      ref: 3.0.1
    pwshlib:
      repo: puppetlabs-pwshlib
      ref: 0.4.1
