---
fixtures:
  symlinks:
    profile: site/profile
    site: "#{source_dir}/site"
  repositories:
    managedmac:
      repo: https://github.com/henrydobson/managedmac
      branch: puppetv4.5
    jackett:
      repo: https://github.com/mergwyn/mergwyn-jackett
      ref: master
    radarr:
      repo: https://github.com/mergwyn/mergwyn-radarr
      ref: master
    ddclient:
      repo: https://github.com/mergwyn/puppet-ddclient
      ref: master
    tvheadend:
      repo: https://github.com/mergwyn/puppet-tvheadend
      ref: master
    transmission:
      repo: https://github.com/mergwyn/puppet-transmission
      ref: master
    webmin:
      repo: https://github.com/rehanone/puppet-webmin
      ref: master
    backuppc:
      repo: https://github.com/mergwyn/mergwyn-backuppc
      branch: puppet6
  forge_modules:
    augeas:
      repo: camptocamp-augeas
      ref: 1.8.0
    kmod:
      repo: camptocamp-kmod
      ref: 2.3.1
    postfix:
      repo: camptocamp-postfix
      ref: 1.8.0
    systemd:
      repo: camptocamp-systemd
      ref: 2.6.0
    network:
      repo: example42-network
      ref: 3.5.1
    portage:
      repo: gentoo-portage
      ref: 2.3.0
    augeasproviders_core:
      repo: herculesteam-augeasproviders_core
      ref: 2.5.0
    augeasproviders_pam:
      repo: herculesteam-augeasproviders_pam
      ref: 2.2.1
    augeasproviders_shellvar:
      repo: herculesteam-augeasproviders_shellvar
      ref: 4.0.0
    samba:
      repo: kakwa-samba
      ref: 2.0.0
    snapd:
      repo: kemra102-snapd
      ref: 1.1.0
    cups:
      repo: mosen-cups
      ref: 1.5.0
    alternatives:
      repo: puppet-alternatives
      ref: 3.0.0
    archive:
      repo: puppet-archive
      ref: 4.1.0
    cron:
      repo: puppet-cron
      ref: 1.3.1
    dhcp:
      repo: puppet-dhcp
      ref: 3.4.0
    apache:
      repo: puppetlabs-apache
      ref: 5.0.0
    apt:
      repo: puppetlabs-apt
      ref: 7.1.0
    augeas_core:
      repo: puppetlabs-augeas_core
      ref: 1.0.4
    firewall:
      repo: puppetlabs-firewall
      ref: 2.0.0
    git:
      repo: puppetlabs-git
      ref: 0.5.0
    inifile:
      repo: puppetlabs-inifile
      ref: 3.1.0
    mailalias_core:
      repo: puppetlabs-mailalias_core
      ref: 1.0.5
    mysql:
      repo: puppetlabs-mysql
      ref: 10.1.0
    ntp:
      repo: puppetlabs-ntp
      ref: 8.0.0
    pe_gem:
      repo: puppetlabs-pe_gem
      ref: 0.2.0
    postgresql:
      repo: puppetlabs-postgresql
      ref: 6.1.0
    puppetdb:
      repo: puppetlabs-puppetdb
      ref: 7.4.0
    reboot:
      repo: puppetlabs-reboot
      ref: 2.2.0
    ruby:
      repo: puppetlabs-ruby
      ref: 1.0.1
    sshkeys_core:
      repo: puppetlabs-sshkeys_core
      ref: 1.0.2
    stdlib:
      repo: puppetlabs-stdlib
      ref: 6.0.0
    translate:
      repo: puppetlabs-translate
      ref: 2.0.0
    vcsrepo:
      repo: puppetlabs-vcsrepo
      ref: 3.0.0
    xinetd:
      repo: puppetlabs-xinetd
      ref: 3.3.0
    yumrepo_core:
      repo: puppetlabs-yumrepo_core
      ref: 1.0.3
    letsencrypt:
      repo: puppet-letsencrypt
      ref: 4.0.0
    nginx:
      repo: puppet-nginx
      ref: 1.0.0
    puppetboard:
      repo: puppet-puppetboard
      ref: 5.0.0
    python:
      repo: puppet-python
      ref: 3.0.1
    r10k:
      repo: puppet-r10k
      ref: 7.0.0
    selinux:
      repo: puppet-selinux
      ref: 3.0.0
    unattended_upgrades:
      repo: puppet-unattended_upgrades
      ref: 4.0.0
    zabbix:
      repo: puppet-zabbix
      ref: 6.7.0
    ssh:
      repo: ghoneycutt-ssh
      ref: 3.61.0
    sudo:
      repo: saz-sudo
      ref: 6.0.0
    timezone:
      repo: saz-timezone
      ref: 5.1.1
    sssd:
      repo: sgnl05-sssd
      ref: 3.0.0
    epel:
      repo: stahnma-epel
      ref: 1.3.1
    debconf:
      repo: stm-debconf
      ref: 2.3.0
    homebrew:
      repo: thekevjames-homebrew
      ref: 1.8.3
    libvirt:
      repo: thias-libvirt
      ref: 1.0.0
    sysctl:
      repo: tpdownes-sysctl
      ref: 2.1.0
    exports:
      repo: zack-exports
      ref: 1.0.1
    host_core:
      repo: puppetlabs-host_core
      ref: 1.0.2
    mount_core:
      repo: puppetlabs-mount_core
      ref: 1.0.3
    bootstrap:
      repo: puppetlabs-bootstrap
      ref: 1.0.0
    exec:
      repo: puppetlabs-exec
      ref: 0.4.0
    chocolatey:
      repo: puppetlabs-chocolatey
      ref: 4.0.0
    dism:
      repo: puppetlabs-dism
      ref: 1.3.1
    powershell:
      repo: puppetlabs-powershell
      ref: 2.3.0
    registry:
      repo: puppetlabs-registry
      ref: 2.1.0
    concat:
      repo: puppetlabs-concat
      ref: 6.1.0
    scheduled_task:
      repo: puppetlabs-scheduled_task
      ref: 1.0.1
