---
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.gitignore:
  required: &ignorepaths
    - '.onceover/'
    - 'spec/fixtures'
.travis.yml:
  branches:
  - production
  - development
  notifications:
    email:
      recipients:
      - gary@theclarkhome.com
      on_success: change # default: change
      on_failure: always # default: always
Gemfile:
  required:
    ':development':
      - gem: rake
      - gem: r10k
      - gem: ra10ke
      - gem: onceover
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 0
  strict_level: ":warning"
  hiera_config: "spec/hiera.yaml" 
Rakefile:
  extras: 
  - require 'ra10ke'
  - require 'onceover/rake_tasks'
  - FastGettext.default_text_domain = 'default-text-domain'
