---
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  branches:
  - production
  - development
  notifications:
    email:
      recipients:
      - gary@theclarkhome.com
      on_success: change # default: change
      on_failure: always # default: always
Gemfile:
  required:
    ':development':
      - gem: rake
      - gem: r10k
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 0
  strict_level: ":warning"
  hiera_config: 'spec/fixtures/hiera.yaml'
