#!/bin/sh

echo $0: $*
fs="
/
"
dirs="
var/log
var/cache
"

echo $0: ${dirs}
for root in ${fs} ; do
  for dir in ${dirs} ; do
    echo ${root}${dir}
    if [ ! -f "${root}${dir}/.sentinel" ] ; then
      touch "${root}${dir}/.sentinel"
    fi
    for d in $(find ${root}${dir} -type d -print) ; do
      echo $d
      cat > ${d}/.rsync-filter <<!
+ */
+ .sentinel
- *
!
    done
  done
done

exit
