#!/bin/bash

LEVEL=$1
DUMPDIR=/var/backups
USER=root
MYSQLADMIN=$(which mysqladmin)
PASSFILE="../${0}-password"
[[ -f  "${PASSFILE}" ]] && . "${PASSFILE}"

echo $0: $*
[ -d "$DUMPDIR" ] || exit 0
[ "$MYSQLADMIN" = "" ] && exit 0

mysqldump -u $USER --password=$PASSWORD --single-transaction --flush-logs --master-data=2 --all-databases --delete-master-logs \
  | gzip > $DUMPDIR/dump.$$.sql.gz

mv $DUMPDIR/dump.$$.sql.gz $DUMPDIR/dump.sql.gz
