#!/bin/bash
# support for boot environments and snapshots

MNTINFO=$(mount | grep 'on / type')
[[ ${MNTINFO} = *zfs* ]] || exit 0
# we have a zfs root file system

BOOTEDROOT=${MNTINFO%% *}
oIFS=$IFS
IFS=/ PARTS=( ${BOOTEDROOT} )
IFS=$oIFS
POOL=${PARTS[0]}
BEDS=${PARTS[1]}
#BE=${PARTS[2]}

MNTDIR=/tmp/grub$$
mkdir ${MNTDIR} || true

declare -i COUNT=0
declare -i INDENT=0

[[ -f /etc/default/grub ]] && . /etc/default/grub
DIST=${GRUB_DISTRIBUTOR:-"Linux"}

echowtabs()
{
  tabs=$1
  shift
  for ((i=0; i<$tabs; i++))
  do
    echo -n "	"
  done
  echo $*
}

make_entry()
{
  local _mntdir=$1
  local _fs=$2
  local _submenu="${3:-}"

  rootfs=${_fs%%@*}
  be=${rootfs##*/}
  snap=${fs#*@}
  snapname=${snap}/
  [[ ${snap} ]] && entry="@${snap}" || entry=""
 
  ${MOUNT} ${_mntdir} >&2
  if [[ -d ${_mntdir}/boot/ ]]
  then
    for version in $(cd ${_mntdir}/boot; ls -t vmlinuz-* | grep -v old-dkms)
    do
      version=$(echo $version | sed 's/^vmlinuz-//')
      if [[ -f ${_mntdir}/boot/vmlinuz-$version && -f ${_mntdir}/boot/initrd.img-$version ]] 
      then
        if [[ ${COUNT} = 0 && ${_submenu} ]]
	then
	  echowtabs ${INDENT} "submenu '${_submenu}' {"
	  (( INDENT++ ))
	fi
        COUNT+=1
	echo "Found kernel image: $version in boot environment ${be}${entry} " >&2 
	echowtabs ${INDENT} "menuentry '${DIST}, ${be}${entry}, with kernel $version ($(zfs list -H -o creation ${_fs}))' {"
	echowtabs ${INDENT}+1 "	linux   /${BEDS}/${be}/@${snapname}boot/vmlinuz-$version root=ZFS=${_fs} ro boot=zfs"
	echowtabs ${INDENT}+1 "	initrd  /${BEDS}/${be}/@${snapname}boot/initrd.img-$version"
	echowtabs ${INDENT} "}"
      fi
    done
  fi
  ${UMOUNT} >&2
}

echo "# Auto generated zfs boot environment and snapshot entries"

BELIST=$({
if [[ $(which beadm) ]]
then
  beadm list -H | cut -f 1 | sed "s:^:${POOL}/${BEDS}/:"
else
  zfs list -H -r -p -o name ${POOL}/${BEDS}
fi
} | tac)
for BE in $BELIST
do
  INDENT=0
  if [[ ${BE} = ${BOOTEDROOT} ]]
  then
    MOUNT=:
    UMOUNT=:
    make_entry "" ${BE} "${DIST}, boot environment ${BE}"
  else
    be="${BE##*/}"
    MOUNT="$(which beadm) mount ${be}"
    UMOUNT="$(which beadm) umount "${be}""
    make_entry ${MNTDIR} ${BE} "${DIST}, boot environment ${BE}"
  fi
#  COUNT=0 # to make sure we don't output empt submenus
#  for fs in $(zfs list -H -r -p -t snap -o name ${BE} | tac)
#  do
#    MOUNT="mount -t zfs ${fs}"
#    UMOUNT="umount ${MNTDIR}"
#    make_entry ${MNTDIR} ${fs} "${DIST}, ${BE} snapshots"
#  done
  until [[ $INDENT = 0 ]]
  do
    (( INDENT-- ))
    echowtabs ${INDENT} "}"
  done
done
rmdir ${MNTDIR}

exit 0

# vim: sw=2:ai:nu 
