#!/bin/bash

LEVEL=$1
DUMPDIR=/var/lib/mysql/log/
USER=root
MYSQLADMIN=`which mysqladmin`
[[ -f  "${0}-password" ]] && . "${0}-password"

echo $0: $*
[ -d "$DUMPDIR" ] || exit 0
[ "$MYSQLADMIN" = "" ] && exit 0

if [ "$LEVEL" = "full" ]
then
    echo $0: full
    mysqldump -u $USER --password=$PASSWORD --single-transaction --flush-logs --master-data=2 --all-databases --delete-master-logs | gzip > $DUMPDIR/dump.$$.sql.gz
    mv $DUMPDIR/dump.$$.sql.gz $DUMPDIR/dump.sql.gz
else
    echo $0: not full
    mysqladmin -u $USER --password=$PASSWORD flush-logs
fi
