# @summary Deploy the shared ZFSBootMenu recovery SSH private key
#
# @description
# Distributes the private half of the shared ZFSBootMenu recovery key (the
# public half is configured separately as an authorized_keys entry via
# profile::platform::baseline::debian::boot::zfsbootmenu::remote_access) to
# nodes that should be able to SSH into any node's pre-boot ZFSBootMenu
# environment - reducing reliance on a KVM-over-IP device for recovery.
#
# The key is stored under /etc/ssh (root-owned, mode 0400), not a user's
# ~/.ssh, so using it requires root/sudo - deliberate, given it can reach
# the boot-time environment of every node it's trusted by.
#
# This class only deploys the key itself. The per-node `Host zbm-<name>`
# aliases (Hostname, Port, IdentityFile, etc.) live in Hiera as
# profile::platform::baseline::debian::ssh::extra_client_options, merged
# into the existing saz-ssh-backed baseline class rather than managed by a
# second, competing ssh_config file here.
#
# Host key verification for the aliases should point at a dedicated
# known_hosts file (this class manages one, empty, at
# /etc/ssh/zbm_recovery_known_hosts) with StrictHostKeyChecking accept-new
# - the first connection to each node is trusted automatically and later
# connections are protected against a changed key, with no manual
# host-key distribution needed. Stricter pinning (the exact host keys are
# already deterministic, generated by boot::zfsbootmenu::remote_access on
# each ZBM node) would be a follow-up, not something this class does today.
#
# @param private_key
#   The recovery keypair's private key, from encrypted Hiera (hiera-eyaml).
#
class profile::platform::baseline::debian::ssh::zbm_recovery (
  Sensitive[String[1]] $private_key,
) {
  file { '/etc/ssh/zbm_recovery':
    ensure    => file,
    owner     => 'root',
    group     => 'root',
    mode      => '0400',
    content   => $private_key,
    show_diff => false,
  }

  file { '/etc/ssh/zbm_recovery_known_hosts':
    ensure  => file,
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    replace => false, # populated by accept-new on first connect to each host - don't clobber it on every run
  }
}
