# vim: sw=2:ai:nu expandtab

alias h=history
alias he='history | egrep'
alias r='fc -s'
alias l='ls -CFsa'
#alias most='du -hsx * | sort -rh | head -10'
#alias most='du -hx --max-depth=1 . | sort -rh | head -10'
alias most='du -kaxh --max-depth=1 | sort -rh | head -10'
alias nodile='pmset noidle'
alias odrive=/opt/odrive/bin/odrive
alias disk_iostat='iostat $(lsblk --nodeps -n -o name --include 8 |sort)'
alias brew='sudo -u brew -i $(which brew)'
alias be='pdk bundle exec'

boldecho() { echo $(tput smso)"$@"$(tput rmso) ; }

set -o vi
