#!/usr/bin/env bash

source /opt/scripts/functions/log.sh
default_owner=default@default

kopiacmd="/opt/scripts/bin/kopiacmd"

source /etc/default/kopia

[[ ${MAINTENANCE} == false ]] && exit 0

for repo in $(${kopiacmd} repo valid kopia) ; do
  log_notice "Starting maintenance for repo: ${repo}"
  LOGLEVEL=WARN ${kopiacmd} repo connect "${repo}"
  export KOPIA_CONFIG_PATH=~/.config/kopia/${repo}.config

  kopia maintenance info

  owner=$(kopia maintenance info --json | jq -er '.owner')
  log_debug "Maintenance owner for repo ${repo} is ${repo}"
  if [[ ${owner##*@} != $(hostname) ]] ; then
    log_warn "Changing maintenance owner for ${repo} from ${owner} to me"
    kopia maintenance set --owner=me 
  fi
  log_info "Running maintenance for ${repo}"
  kopia maintenance run --full
  if [[ -z ${owner} ]]  ; then
    owner="default@default"
    log_warn "Maintenance user for ${repo} not set, changing to ${owner}"
  fi
  log_info "Resetting maintenance user for ${repo} to ${owner}"
  kopia maintenance set --owner="${owner:-${default_owner}}"
  unset KOPIA_CONFIG_PATH
  log_notice "Maintenance complete for repo: ${repo}"
done


for repo in $(${kopiacmd} repo valid velero) ; do
  # kopia maintenance is handled by velero
  log_notice "Cleaning policies for repo: ${repo}"
  LOGLEVEL=WARN ${kopiacmd} repo connect "${repo}"
  export KOPIA_CONFIG_PATH=~/.config/kopia/${repo}.config

  # reset owner if needed
  owner=$(kopia maintenance info --json | jq -er '.owner')
  log_debug "Maintenance owner for repo ${repo} is ${repo}"
  if [[ ${owner} != default@default ]] ; then
    log_warn "owner is ${owner,} reset to default@default"
    kopia maintenance set --owner=default@default
  fi

  # Delete orphaned policies
  for policy in $(kopia policy list | cut -d ' ' -f 2) ; do
    if [[ $(kopia snapshot list --all | grep -c ${policy}) == 0 ]] ; then
      kopia policy delete ${policy}
    fi
  done
done


