#!/usr/bin/env bash

source /opt/scripts/functions/log.sh

too_old="36 hours ago"

source /etc/default/kopia
kopiacmd=/opt/scripts/bin/kopiacmd

# Refresh certificates
# LOGLEVEL=WARN ${kopiacmd} system certs > /dev/null

for repo in ${REPOS} ; do
  log_debug Connecting to repo ${repo}
  LOGLEVEL=WARN ${kopiacmd} repo connect ${repo}

  [[ ${repo} != filesystem ]] 
  log_info "Starting backup for repo: ${repo}"
  export KOPIA_CONFIG_PATH=~/.config/kopia/${repo}.config

  # SNAPS is a comma separated list of directories to backup
  log_debug backup list ${SNAPS}
  IFS=, read -ra snaparray <<< "${SNAPS}"
  for snap in "${snaparray[@]}"; do
    log_info "Creating snapshot ${snap} in ${repo}"
    kopia snapshot create ${ARGS} "${snap}" 2>&1 | grep -v 'unknown or unsupported entry type'
  done

  unset KOPIA_CONFIG_PATH
  log_info "Backup complete for repo: ${repo}"

done
