#!/usr/bin/env bash
PATH=$PATH:$(dirname "$0")

boldecho() { echo "$(tput smso)$*$(tput rmso)" ; }

for container in $(listcontainers); do
  boldecho executing: lxc exec "${container}" -- bash -c "$*" >&2
  lxc exec "${container}" -- bash -c "$*" 
done
