#!/usr/bin/env bash

if [[ $# -gt 0 ]] ; then
  REMOTES=( "$@" )
else
  mapfile -t  REMOTES < <(listremotes) 
fi
for remote in "${REMOTES[@]}" ; do
  for c in $(lxc list "${remote}:" --format=json | jq -r '.[] | select(.state.status == "Running") | .name '); do
    printf "%s:%s\n" ${remote} ${c}
  done
done
