name: "Spec Tests"

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
  pull_request:
  push:
    branches:
      production

#concurrency:
#  group: ${{ github.head_ref }}
#  cancel-in-progress: true

jobs:
  setup_matrix:
    name: "Setup Test Matrix"
    runs-on: ubuntu-20.04
    outputs:
      spec_matrix: ${{ steps.get-matrix.outputs.spec_matrix }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        if: ${{ github.repository_owner == 'mergwyn' }}

      - name: Activate Ruby 2.7
        uses: ruby/setup-ruby@v1
        if: ${{ github.repository_owner == 'mergwyn' }}
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: Print bundle environment
        if: ${{ github.repository_owner == 'mergwyn' }}
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::
      - name: Run Static & Syntax Tests
        if: ${{ github.repository_owner == 'mergwyn' }}
        run: |
          bundle exec rake validate lint check rubocop

      - name: Setup Spec Test Matrix
        id: get-matrix
        run: |
          if [ '${{ github.repository_owner }}' == 'mergwyn' ]; then
            bundle exec matrix_from_metadata_v2 --exclude-platforms '["Darwin-18","Darwin-20","windows-10","windows-11"]'
          else
            echo  "::set-output name=spec_matrix::{}"
          fi
  Spec:
    name: "Spec Tests (Puppet: ${{matrix.puppet_version}}, Ruby Ver: ${{matrix.ruby_version}})"
    needs:
      - setup_matrix
    if: ${{ needs.setup_matrix.outputs.spec_matrix != '{}' }}

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup_matrix.outputs.spec_matrix)}}

    env:
      BUILDEVENT_FILE: '../buildevents.txt'
      PUPPET_GEM_VERSION: ${{ matrix.puppet_version }}
      FACTER_GEM_VERSION: 'https://github.com/puppetlabs/facter#main'

    steps:
      - run: |
          echo "SANITIZED_PUPPET_VERSION=$(echo '${{ matrix.puppet_version }}' | sed 's/~> //g')" >> $GITHUB_ENV

      - run: |
          echo 'puppet_version=${{ env.SANITIZED_PUPPET_VERSION }}' >> $BUILDEVENT_FILE
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: "Activate Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby_version}}
          bundler-cache: true

      - name: Print bundle environment
        run: |
          echo ::group::bundler environment
          bundle env
          echo ::endgroup::

      - name: Run parallel_spec tests
        run: |
          bundle exec rake parallel_spec
